### ISSUE TITLE
unexpectedToken error when parsing paths with plus symbols

### ISSUE THREAD

**Issue by rustyshelf** [nicklockwood/SVGPath#5]
Some tools like Inkpad sometimes generate paths with + symbols in them that look like this:
```
d="M724.369+45.4351C724.369-30.8713+786.228-92.7298+862.534-92.7298C938.841-92.7298+1000.7-30.8713+1000.7+45.4351C1000.7+121.742+938.841+183.6+862.534+183.6C786.228+183.6+724.369+121.742+724.369+45.4351Z"
```

From what I can tell these appear to be valid in most other SVG parsers. SVGPath however generates an unexpectedToken on parsing the above (`unexpectedToken("724.369+45")`) and a lot of the paths in this SVG:
[Toucan in the Shade.svg.zip](https://github.com/nicklockwood/SVGPath/files/10976341/Toucan.in.the.Shade.svg.zip)

**Comment by nicklockwood** [comment]
@rustyshelf fixed in 1.1.3
