### ISSUE TITLE
Arc rotation gives unexpected result

### ISSUE THREAD

**Issue by huse360** [nicklockwood/SVGPath#6]
The following path (pay attention to the -10 rotation parameter)

```
<path d="
        m 150 250
        a 150 170 0 1 1 0 -0.0001
        a 150 340 -10 0 0 -190 -400
        "
      />
```

should give this expected result:

<img width="352" alt="image" src="https://github.com/nicklockwood/SVGPath/assets/7477778/688e4979-3cf6-4315-89d5-cf75df51050b">

But this the actual result:

<img width="289" alt="image" src="https://github.com/nicklockwood/SVGPath/assets/7477778/64b39e2e-65ae-4598-9612-688fa2b5bdab">

**Comment by nicklockwood** [comment]
@huse360 fixed in 1.1.4
